---
- name: Setup global hosts
  lineinfile: dest=/etc/hosts
              line="{{item}}"
              state=present
              owner=root
              group=root
              mode=0644
  with_items: base_global_hosts
  when: base_global_hosts is defined

- name: "Setup hostname"
  hostname: name="{{ec2_host_Name}}"
  when: ec2_host_Name is defined
  ignore_errors: "{{ base_ignore_hostname_setup_error }}"

- name: "Set facts with hostname"
  set_fact: ansible_hostname="{{ec2_host_Name}}"
  when: ec2_host_Name is defined

- name: "Check if cloud.cfg is present"
  stat: path=/etc/cloud/cloud.cfg
  register: etc_cloud_cloud_cfg

- name: "Persist hostname through cloudinit"
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:.*$'
    line: "preserve_hostname: yes"
  when: etc_cloud_cloud_cfg.stat.exists is defined

- name: "Setup AWS Hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ item }}.*{{ base_hosts_suffix }}'
    line: "{{ item }} {{hostvars[item].ec2_tag_Name}} {{base_custom_hosts[hostvars[item].ec2_tag_Name]|default([])|join(' ')}} {{ base_hosts_suffix }}"
    state: present
  with_items: "{{ play_hosts }}"
  when: ec2_tag_Name is defined and base_manage_host_file

- pip: name=boto state=latest

- name: "Register instance private DNS"
  route53:
    command: "create"
    zone: "{{ base_r53_internal_zone }}"
    record: "{{ ec2_tag_Name }}.{{ base_r53_internal_zone }}"
    type: "A"
    ttl: "7200"
    value: "{{ ansible_eth0.ipv4.address }}"
    private_zone: true
    overwrite: true
  when: base_r53_internal_zone is defined and ec2_tag_Name is defined and base_manage_host_r53
  delegate_to: 127.0.0.1
  ignore_errors: yes
